package stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-19T23:21:12.565+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "DeliveryWebServiceService", 
                  wsdlLocation = "file:/D:/Users/Utilisateur/Documents/GitHub/projet-isa-devops-20-team-n-20/client/src/main/resources/DeliveryWebService.wsdl",
                  targetNamespace = "http://www.n.team.polytech.fr/deliverywebservice/") 
public class DeliveryWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.n.team.polytech.fr/deliverywebservice/", "DeliveryWebServiceService");
    public final static QName DeliveryWebServicePort = new QName("http://www.n.team.polytech.fr/deliverywebservice/", "DeliveryWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Users/Utilisateur/Documents/GitHub/projet-isa-devops-20-team-n-20/client/src/main/resources/DeliveryWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeliveryWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Users/Utilisateur/Documents/GitHub/projet-isa-devops-20-team-n-20/client/src/main/resources/DeliveryWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeliveryWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeliveryWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DeliveryWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DeliveryWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DeliveryWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DeliveryWebService
     */
    @WebEndpoint(name = "DeliveryWebServicePort")
    public DeliveryWebService getDeliveryWebServicePort() {
        return super.getPort(DeliveryWebServicePort, DeliveryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryWebService
     */
    @WebEndpoint(name = "DeliveryWebServicePort")
    public DeliveryWebService getDeliveryWebServicePort(WebServiceFeature... features) {
        return super.getPort(DeliveryWebServicePort, DeliveryWebService.class, features);
    }

}
