package stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-19T23:21:12.537+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://www.n.team.polytech.fr/deliverywebservice/", name = "DeliveryWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeliveryWebService {

    @WebMethod
    @RequestWrapper(localName = "planDelivery", targetNamespace = "http://www.n.team.polytech.fr/deliverywebservice/", className = "stubs.PlanDelivery")
    @ResponseWrapper(localName = "planDeliveryResponse", targetNamespace = "http://www.n.team.polytech.fr/deliverywebservice/", className = "stubs.PlanDeliveryResponse")
    @WebResult(name = "package_information", targetNamespace = "")
    public java.lang.String planDelivery(
        @WebParam(name = "calendar", targetNamespace = "")
        int calendar,
        @WebParam(name = "idPackage", targetNamespace = "")
        int idPackage
    );
}
